python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/sev_tox01.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/sev_tox02.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/sev_tox03.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/sev_tox04.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/sev_tox05.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/sev_tox06.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/sev_tox07.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/sev_tox08.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/sev_tox09.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/sev_tox10.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/sev_tox11.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/sev_tox12.cfg