python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/seq_bgrux1_emb1.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/seq_bgrux1_emb2.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/seq_bgrux1_emb3.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/seq_bgrux1_emb4.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/seq_bgrux1_emb5.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/seq_bgrux1_emb6.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/seq_bgrux1_emb7.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/seq_bgrux1_emb8.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/seq_bgrux1_emb9.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/seq_bgrux1_emb10.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/seq_bgrux1_emb11.cfg
python main.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/seq_bgrux1_emb12.cfg
python main2.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/com_bgrux1_emb1.cfg
python main2.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/com_bgrux1_emb2.cfg
python main2.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/com_bgrux1_emb3.cfg
python main2.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/com_bgrux1_emb4.cfg
python main2.py --train ../data/train_processed.csv --test ../data/test_processed.csv --config cfgs/com_bgrux1_emb5.cfg